update pycharm professional -> 2018.1.2
FZUG/repo pull request #305
Opened 2018-05-05 04:38 UTC by duriantang

更新 **pycharm professional** 到 ``2018.1.2``

* 去掉了不必要的依赖
* 使用自带的jre64，所以去掉了jre的依赖

2018-05-07 04:41 UTC, sztsian commented
This can be built.
The same as #304 , please update the bundle info according to  https://fedoraproject.org/wiki/Bundled_Libraries#Requirement_if_you_bundle

2018-05-08 08:12 UTC, sztsian requested changes

2018-05-08 08:12 UTC, sztsian commented on rpms/JetBrains/PyCharm-professional.spec
> +Provides: bundled(jre) = 1.8.0_152-release
这儿就不需要了吧。
此外，为啥改历史的 log 啊（ vi 的 P 没按 shift? XD)

2018-05-08 09:08 UTC, duriantang reviewed
已经还原了。

2018-05-08 09:08 UTC, duriantang commented on rpms/JetBrains/PyCharm-professional.spec
> +Provides: bundled(jre) = 1.8.0_152-release
不小心，再加上commit的时候没有检查，已经还原了。

2018-05-08 09:54 UTC, sztsian approved these changes
LGTM

2018-05-08 09:54 UTC, merged