New pkg request: GN
FZUG/repo pull request #352
Opened 2019-04-18 19:22 UTC by dengbangjie

# GN

## Description  
GN is a meta-build system that generates build files for Ninja. It is widely used by repos related to Google, such as chromium, qcef , etc.

## Benefits
Make it easily for fedora users to build qcef, pdfium, etc.

2019-04-19 12:39 UTC, sztsian requested changes

2019-04-19 12:39 UTC, sztsian commented on rpms/gn/gn.spec
> +Version:        1559
I don't see any releases for this project, so I feel you should use the way for [upstream has never choose a version](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_upstream_has_never_chosen_a_version). In this case, I suggest you to use 
```
Version:        0
Release:        1.git%{shortcommit}%{?dist}
```

Or similar things like
```
Version:        0
Release:        1.1559git%{shortcommit}%{?dist}
```

2019-04-19 12:39 UTC, sztsian commented on rpms/gn/gn.spec
> +Version:        1559
Adding @cheese to see which is a better version.

2019-04-19 19:13 UTC, dengbangjie commented
I correct to `Version: 0` and `1.1559git%{shortcommit}%{?dist}` .

2019-04-20 04:44 UTC, sztsian commented
Looks good now. I'm merging for the moment and will see if there are build failures tomorrow.

2019-04-20 04:44 UTC, merged