nvchecker@2.7
FZUG/repo pull request #382
Opened 2022-02-26 18:15 UTC by zhullyb

2022-02-27 00:35 UTC, alick commented on rpms/nvchecker/nvchecker.spec
> +%{_bindir}/nv*
这样有点危险吧，如果其他包有nv开头的命令呢？

2022-02-27 05:33 UTC, zhullyb commented on rpms/nvchecker/nvchecker.spec
> +%{_bindir}/nv*
历史其他包有nv开头的命令，那也不会出现在这个包构建时的buildroot中吧？

2022-03-03 12:24 UTC, sztsian requested changes

2022-03-03 12:24 UTC, sztsian commented on rpms/nvchecker/nvchecker.spec
> +Source0:        https://github.com/lilydjwg/nvchecker/archive/refs/tags/v2.7.tar.gz
建议把这个 `v2.7.tar.gz` 换成 `v%{version}.tar.gz`

2022-03-03 12:24 UTC, sztsian commented on rpms/nvchecker/nvchecker.spec
> +Obsoletes:      python3-%{name} <= %{version}
同名的包不需要 obsoletes 吧？

2022-03-03 12:24 UTC, sztsian commented on rpms/nvchecker/nvchecker.spec
> +%define BUILD_DIR %{_builddir}/%{name}-%{version}
这儿拆分成两步主要目的是什么呢？

2022-03-03 12:24 UTC, sztsian commented on rpms/nvchecker/nvchecker.spec
> +%{_bindir}/nv*
不建议用如此模糊的通配符。不是因为怕把其他文件引入，而是不便于打包者发觉添加了什么新二进制。虽然在 FZUG Repo 这个大概没人关注地那么仔细。。。。

2022-03-03 12:24 UTC, sztsian commented on rpms/nvchecker/nvchecker.spec
> -%{_bindir}/nvtake
以前既然是分开的，就还是分开写吧

2022-03-03 15:20 UTC, sztsian commented
Looks good now. Thanks!

2022-03-03 15:20 UTC, merged